fixed critical bug, because of this line: `db.rollback()`
the error log said:
ERROR: Internal Server Error:
Traceback (most recent call last):
  File "build\bdist.win32\egg\trac\web\main.py", line 478, in _dispatch_request
    dispatcher.dispatch(req)
  File "build\bdist.win32\egg\trac\web\main.py", line 198, in dispatch
    resp = chosen_handler.process_request(req)
  File "build\bdist.win32\egg\xmail\XMailMainView.py", line 99, in process_request
    return self.print_main_view(req)
  File "build\bdist.win32\egg\xmail\XMailMainView.py", line 207, in print_main_view
    rows, col_list = self.get_data(sql)
  File "build\bdist.win32\egg\xmail\XMailMainView.py", line 340, in get_data
    db.rollback()
  File "build\bdist.win32\egg\trac\db\util.py", line 107, in __getattr__
    raise AttributeError
AttributeError: